version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
 
  post_build:
    commands:
      - zip -r build.zip . -x "node_modules/*"
artifacts:
  files:
    - build.zip
  discard-paths: yes
